"""Init Schema

Revision ID: dcacf664b954
Revises: 
Create Date: 2026-05-21 01:32:33.791911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcacf664b954'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=255), nullable=False),
    sa.Column('is_kids', sa.Boolean(), nullable=True),
    sa.Column('pin_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('continue_watching',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('poster', sa.String(length=500), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'content_id', 'content_type', name='uq_profile_continue')
    )
    with op.batch_alter_table('continue_watching', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_continue_watching_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_continue_watching_profile_id'), ['profile_id'], unique=False)

    op.create_table('recently_watched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('poster', sa.String(length=500), nullable=True),
    sa.Column('watched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recently_watched', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recently_watched_profile_id'), ['profile_id'], unique=False)

    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('searched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_history_profile_id'), ['profile_id'], unique=False)

    op.drop_table('user')
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_watchlist_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_profile_id'), ['profile_id'], unique=False)
        batch_op.create_unique_constraint('uq_profile_content', ['profile_id', 'content_id', 'content_type'])
        batch_op.create_foreign_key('fk_watchlist_profile_id', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_watchlist_profile_id', type_='foreignkey')
        batch_op.drop_constraint('uq_profile_content', type_='unique')
        batch_op.drop_index(batch_op.f('ix_watchlist_profile_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_content_id'))
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('content_id',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('added_at')
        batch_op.drop_column('profile_id')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=True),
    sa.Column('password', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_history_profile_id'))

    op.drop_table('search_history')
    with op.batch_alter_table('recently_watched', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recently_watched_profile_id'))

    op.drop_table('recently_watched')
    with op.batch_alter_table('continue_watching', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_continue_watching_profile_id'))
        batch_op.drop_index(batch_op.f('ix_continue_watching_content_id'))

    op.drop_table('continue_watching')
    op.drop_table('profiles')
    # ### end Alembic commands ###
